config/routes.rb
Rails.application.routes.draw do
  resources :municipalities
  get 'municipalities_list', to: 'municipalities#list', as: 'municipalities_by_department'
  resources :departments
  resources :pieces
  resources :villages
  get 'villages_list', to: 'villages#list', as: 'villages_by_municipality'
  resources :deliveries
  resources :parameters
  resources :transactions do
    resources :transaction_details
    post 'close_order', to: 'close_order', as: 'close_order'
    post 'change_status', to: 'change_status', as: 'change_status'
    post 'devolucion', to: 'devolucion', as: 'devolucion'
    post 'not_delivery', to: 'not_delivery', as: 'not_delivery'
    get '/view_tracking', to: 'transactions#view_tracking', as: 'view_tracking'
    post '/return_stock', to: 'transactions#return_to_stock', as: 'return_to_stock'
  end
  get '/delivered', to: 'transactions#delivered', as: 'delivered'
  get '/pendings', to: 'transactions#pendings', as: 'pendings'
  get '/pendings_not', to: 'transactions#pendings_not', as: 'pendings_not_delivered'
  get '/on_route', to: 'transactions#on_route', as: 'on_route'
  post '/asign_courier', to: 'transactions#asign_courier', as: 'asign_courier'
  get '/restocks', to: 'transactions#restocks', as: 'restocks'
  resources :products
  devise_for :dealers, controllers: {
    sessions: 'dealers/sessions'
  }
  resources :statuses
  resources :carriers
  resources :characteristics
  resources :categories
  resources :dealers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'product_availability', to: 'inventory_utils#check_inventory_qty', as: 'product_availability'
    end
  end

  get '/reports', to: 'reports#index', as: 'reports'
  get '/earning', to: 'reports#earning_report', as: 'earning_report'
  get '/delivery', to: 'reports#delivery_report', as: 'delivery_report'

  root 'dashboard#index'
end

app/models/village.rb
# frozen_string_literal: true

class Village < ApplicationRecord
  include CustomName
end

app/controllers/villages_controller.rb
class VillagesController < ApplicationController
  before_action :set_village, only: [:show, :edit, :update, :destroy]
  before_action :list_params, only: %w[list]
  skip_before_action :not_admin

  # GET /villages
  # GET /villages.json
  def index
    @villages = Village.all
  end

  # GET /villages/1
  # GET /villages/1.json
  def show
  end

  # GET /villages/new
  def new
    @village = Village.new
  end

  # GET /villages/1/edit
  def edit
  end

  # POST /villages
  # POST /villages.json
  def create
    @village = Village.new(village_params)

    respond_to do |format|
      if @village.save
        format.html { redirect_to @village, notice: 'Village was successfully created.' }
        format.json { render :show, status: :created, location: @village }
      else
        format.html { render :new }
        format.json { render json: @village.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /villages/1
  # PATCH/PUT /villages/1.json
  def update
    respond_to do |format|
      if @village.update(village_params)
        format.html { redirect_to @village, notice: 'Village was successfully updated.' }
        format.json { render :show, status: :ok, location: @village }
      else
        format.html { render :edit }
        format.json { render json: @village.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villages/1
  # DELETE /villages/1.json
  def destroy
    @village.destroy
    respond_to do |format|
      format.html { redirect_to villages_url, notice: 'Village was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list
    @villages = Village.where(department_id: list_params[:department_id], municipality_id: list_params[:municipality_id])
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_village
      @village = Village.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def village_params
      params.require(:village).permit(:cod, :name, :department_id, :municipality_id)
    end

    def list_params
      params.permit(:department_id, :municipality_id)
    end
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/_form.html.haml
= form_for @village do |f|
  - if @village.errors.any?
    #error_explanation
      %h2= "#{pluralize(@village.errors.count, "error")} prohibited this village from being saved:"
      %ul
        - @village.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :cod
    = f.text_field :cod
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :department_id
    = f.text_field :department_id
  .field
    = f.label :municipality_id
    = f.text_field :municipality_id
  .actions
    = f.submit 'Save'

app/views/villages/edit.html.haml
%h1 Editing village

= render 'form'

= link_to 'Show', @village
\|
= link_to 'Back', villages_path

app/views/villages/index.html.haml
%h1 Listing villages

%table
  %thead
    %tr
      %th Cod
      %th Name
      %th Department
      %th Municipality
      %th
      %th
      %th

  %tbody
    - @villages.each do |village|
      %tr
        %td= village.cod
        %td= village.name
        %td= village.department_id
        %td= village.municipality_id
        %td= link_to 'Show', village
        %td= link_to 'Edit', edit_village_path(village)
        %td= link_to 'Destroy', village, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Village', new_village_path

app/views/villages/new.html.haml
%h1 New village

= render 'form'

= link_to 'Back', villages_path

app/views/villages/show.html.haml
%p#notice= notice

%p
  %b Cod:
  = @village.cod
%p
  %b Name:
  = @village.name
%p
  %b Department:
  = @village.department_id
%p
  %b Municipality:
  = @village.municipality_id

= link_to 'Edit', edit_village_path(@village)
\|
= link_to 'Back', villages_path