config/routes.rb
Rails.application.routes.draw do
  resources :municipalities
  get 'municipalities_list', to: 'municipalities#list', as: 'municipalities_by_department'
  resources :departments
  resources :pieces
  resources :villages
  get 'villages_list', to: 'villages#list', as: 'villages_by_municipality'
  resources :deliveries
  resources :parameters
  resources :transactions do
    resources :transaction_details
    post 'close_order', to: 'close_order', as: 'close_order'
    post 'change_status', to: 'change_status', as: 'change_status'
    post 'devolucion', to: 'devolucion', as: 'devolucion'
    post 'not_delivery', to: 'not_delivery', as: 'not_delivery'
    get '/view_tracking', to: 'transactions#view_tracking', as: 'view_tracking'
    post '/return_stock', to: 'transactions#return_to_stock', as: 'return_to_stock'
  end
  get '/delivered', to: 'transactions#delivered', as: 'delivered'
  get '/pendings', to: 'transactions#pendings', as: 'pendings'
  get '/pendings_not', to: 'transactions#pendings_not', as: 'pendings_not_delivered'
  get '/on_route', to: 'transactions#on_route', as: 'on_route'
  post '/asign_courier', to: 'transactions#asign_courier', as: 'asign_courier'
  get '/restocks', to: 'transactions#restocks', as: 'restocks'
  resources :products
  devise_for :dealers, controllers: {
    sessions: 'dealers/sessions'
  }
  resources :statuses
  resources :carriers
  resources :characteristics
  resources :categories
  resources :dealers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'product_availability', to: 'inventory_utils#check_inventory_qty', as: 'product_availability'
    end
  end

  get '/reports', to: 'reports#index', as: 'reports'
  get '/earning', to: 'reports#earning_report', as: 'earning_report'
  get '/delivery', to: 'reports#delivery_report', as: 'delivery_report'

  root 'dashboard#index'
end

app/models/municipality.rb
class Municipality < ApplicationRecord
  include CustomName
  has_many :villages, class_name: :Village, foreign_key: :municipality_id, primary_key: :cod
end

app/controllers/municipalities_controller.rb
class MunicipalitiesController < ApplicationController
  before_action :set_municipality, only: [:show, :edit, :update, :destroy]
  before_action :list_params, only: %w[list]
  skip_before_action :not_admin

  # GET /municipalities
  # GET /municipalities.json
  def index
    @municipalities = Municipality.all
  end

  # GET /municipalities/1
  # GET /municipalities/1.json
  def show
  end

  # GET /municipalities/new
  def new
    @municipality = Municipality.new
  end

  # GET /municipalities/1/edit
  def edit
  end

  # POST /municipalities
  # POST /municipalities.json
  def create
    @municipality = Municipality.new(municipality_params)

    respond_to do |format|
      if @municipality.save
        format.html { redirect_to @municipality, notice: 'Municipality was successfully created.' }
        format.json { render :show, status: :created, location: @municipality }
      else
        format.html { render :new }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /municipalities/1
  # PATCH/PUT /municipalities/1.json
  def update
    respond_to do |format|
      if @municipality.update(municipality_params)
        format.html { redirect_to @municipality, notice: 'Municipality was successfully updated.' }
        format.json { render :show, status: :ok, location: @municipality }
      else
        format.html { render :edit }
        format.json { render json: @municipality.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /municipalities/1
  # DELETE /municipalities/1.json
  def destroy
    @municipality.destroy
    respond_to do |format|
      format.html { redirect_to municipalities_url, notice: 'Municipality was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def list
    department = Department.find_by_cod(list_params[:department_id])
    @municipalities = department.municipalities
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_municipality
      @municipality = Municipality.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def municipality_params
      params.require(:municipality).permit(:cod, :name, :deptarment_id, :header_id)
    end

    def list_params
      params.permit(:department_id)
    end
end

app/helpers/municipalities_helper.rb
module MunicipalitiesHelper
end

app/views/municipalities/_form.html.haml
= form_for @municipality do |f|
  - if @municipality.errors.any?
    #error_explanation
      %h2= "#{pluralize(@municipality.errors.count, "error")} prohibited this municipality from being saved:"
      %ul
        - @municipality.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :cod
    = f.text_field :cod
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :deptarment_id
    = f.text_field :deptarment_id
  .field
    = f.label :header_id
    = f.text_field :header_id
  .actions
    = f.submit 'Save'

app/views/municipalities/edit.html.haml
%h1 Editing municipality

= render 'form'

= link_to 'Show', @municipality
\|
= link_to 'Back', municipalities_path

app/views/municipalities/index.html.haml
%h1 Listing municipalities

%table
  %thead
    %tr
      %th Cod
      %th Name
      %th Deptarment
      %th Header
      %th
      %th
      %th

  %tbody
    - @municipalities.each do |municipality|
      %tr
        %td= municipality.cod
        %td= municipality.name
        %td= municipality.department_id
        %td= municipality.header_id
        %td= link_to 'Show', municipality
        %td= link_to 'Edit', edit_municipality_path(municipality)
        %td= link_to 'Destroy', municipality, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Municipality', new_municipality_path

app/views/municipalities/new.html.haml
%h1 New municipality

= render 'form'

= link_to 'Back', municipalities_path

app/views/municipalities/show.html.haml
%p#notice= notice

%p
  %b Cod:
  = @municipality.cod
%p
  %b Name:
  = @municipality.name
%p
  %b Deptarment:
  = @municipality.deptarment_id
%p
  %b Header:
  = @municipality.header_id

= link_to 'Edit', edit_municipality_path(@municipality)
\|
= link_to 'Back', municipalities_path