config/routes.rb
Rails.application.routes.draw do
  resources :municipalities
  get 'municipalities_list', to: 'municipalities#list', as: 'municipalities_by_department'
  resources :departments
  resources :pieces
  resources :villages
  get 'villages_list', to: 'villages#list', as: 'villages_by_municipality'
  resources :deliveries
  resources :parameters
  resources :transactions do
    resources :transaction_details
    post 'close_order', to: 'close_order', as: 'close_order'
    post 'change_status', to: 'change_status', as: 'change_status'
    post 'devolucion', to: 'devolucion', as: 'devolucion'
    post 'not_delivery', to: 'not_delivery', as: 'not_delivery'
    get '/view_tracking', to: 'transactions#view_tracking', as: 'view_tracking'
    post '/return_stock', to: 'transactions#return_to_stock', as: 'return_to_stock'
  end
  get '/delivered', to: 'transactions#delivered', as: 'delivered'
  get '/pendings', to: 'transactions#pendings', as: 'pendings'
  get '/pendings_not', to: 'transactions#pendings_not', as: 'pendings_not_delivered'
  get '/on_route', to: 'transactions#on_route', as: 'on_route'
  post '/asign_courier', to: 'transactions#asign_courier', as: 'asign_courier'
  get '/restocks', to: 'transactions#restocks', as: 'restocks'
  resources :products
  devise_for :dealers, controllers: {
    sessions: 'dealers/sessions'
  }
  resources :statuses
  resources :carriers
  resources :characteristics
  resources :categories
  resources :dealers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'product_availability', to: 'inventory_utils#check_inventory_qty', as: 'product_availability'
    end
  end

  get '/reports', to: 'reports#index', as: 'reports'
  get '/earning', to: 'reports#earning_report', as: 'earning_report'
  get '/delivery', to: 'reports#delivery_report', as: 'delivery_report'

  root 'dashboard#index'
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

class TransactionsController < ApplicationController
  before_action :set_transaction, only: %w[show edit update destroy close_order change_status devolucion not_delivery view_tracking asign_courier return_to_stock]
  skip_before_action :not_admin

  # GET /transactions
  # GET /transactions.json
  def index
    if current_dealer.admin?
      @transactions_query = Transaction.where(type: Parameter.transaction_type_out).order(id: :desc).ransack(params[:q])
      @transactions_query_report = Transaction.report_all.where(type: Parameter.transaction_type_out).order(id: :desc).ransack(params[:q])
    elsif current_dealer.grocer?
      @transactions_query = Transaction.pending_to_packing('SALE').ransack(params[:q])
      @transactions_query_report = Transaction.report_all.pending_to_packing('SALE').ransack(params[:q])
    elsif current_dealer.courier?
      @transactions_query = Transaction.pending_to_deliver('SALE', current_dealer.id).ransack(params[:q])
      @transactions_query_report = Transaction.report_all.pending_to_deliver('SALE', current_dealer.id).ransack(params[:q])
    else
      @transactions_query = current_dealer.transactions.ransack(params[:q])
      @transactions_query_report = current_dealer.transactions.report_all.ransack(params[:q])
    end
    @transactions = @transactions_query.result(distinct: true).page(params[:page])
    @transactions_report = @transactions_query_report.result(distinct: true).page(params[:page])
    #raise
    #unless params[:q].present?
    #  @transactions = @transactions_query.result.where('DATE(CREATED_AT) = ?', Date.today)
    #end
    gon.status_filter = params[:q][:status_id] unless params[:q].nil?
    #raise @transactions_report.to_json
    respond_to do |format|
      format.html
      format.csv { send_data Transaction.to_csv(@transactions_report), filename: "transactions-#{DateTime.now}.csv" }
    end
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show; end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
    gon.type_param = type_param
    gon.is_grocer = current_dealer.grocer?
    if type_param[:type].to_i == Parameter.transaction_type_in.first.int_value
      @transaction.status = Status.initial('SALE').first
      @transaction.type = Parameter.transaction_type_in.first
      @transaction.dealer = current_dealer
      if @transaction.save
        redirect_to transaction_transaction_details_path(@transaction)
      end
    end
  end

  # GET /transactions/1/edit
  def edit
    gon.type_param = @transaction.type
    gon.is_grocer = current_dealer.grocer?
    gon.internal_delivery = @transaction.carrier.internal
    gon.carrier_id = @transaction.carrier_id
  end

  # POST /transactions
  # POST /transactions.json
  def create
    created = Delivery::Create.call(params, current_dealer, transaction_params)
    log = ActionLog.new
    log.transaction_id = created.id
    log.user_id = current_dealer.id
    log.user_name = current_dealer.email
    log.action = "Order created"
    log.date_time = DateTime.now
    log.save
    respond_to do |format|
      if created
        format.html { redirect_to transaction_transaction_details_path(created), notice: t('forms.created', model: Transaction.model_name.human) }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /transactions/close_order
  def close_order
    log = ActionLog.new
    log.transaction_id = @transaction.id
    log.user_id = current_dealer.id
    log.user_name = current_dealer.email
    log.action = "Orden cerrada"
    log.date_time = DateTime.now
    log.save
    if @transaction.transaction_details.empty?
      respond_to do |format|
        format.html { redirect_to transaction_transaction_details_path(@transaction), notice: t('activerecord.errors.messages.must_have_child'), alert: true }
        format.json { render json: @transaction_detail.errors, status: :unprocessable_entity }
      end
    else
      if @transaction.type_id == Parameter.transaction_type_out.first.int_value && @transaction.carrier.name == 'Cargo Expreso'
        @transaction.amount = TransactionDetail.get_total_order(@transaction.id).first.total_order
        @transaction.status = @transaction.status.parent
        @transaction.save
        delivery_ok = Delivery::Send.call(@transaction)
        respond_to do |format|
          if delivery_ok
            format.html { redirect_to transactions_path }
            format.json { render :show, status: :created, location: @transaction_detail }
          else
            format.html { redirect_to transaction_transaction_details_path(@transaction), notice: 'Error generando la guía a cargo expreso.', alert: true }
            format.json { render json: @transaction_detail.errors, status: :unprocessable_entity }
          end
        end && return
      end
      @transaction.amount = TransactionDetail.get_total_order(@transaction.id).first.total_order
      @transaction.status = @transaction.status.parent
      respond_to do |format|
        if @transaction.save
          format.html { redirect_to transactions_path }
          format.json { render :show, status: :created, location: @transaction_detail }
        else
          format.html { render :new }
          format.json { render json: @transaction_detail.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # POST /transactions/change_status
  def change_status
    log = ActionLog.new
    log.transaction_id = @transaction.id
    log.user_id = current_dealer.id
    log.user_name = current_dealer.email
    if @transaction.status.parent == Transaction.find_by_description('EN RUTA')
      respond_to do |format|
        format.html { redirect_to delivery_path }
      end
    end
    @transaction_liq = @transaction.status.parent
    log.action = "Change status #{@transaction.status.description} to #{@transaction.status.parent.description}"
    log.date_time = DateTime.now
    log.save
    @transaction.status = @transaction.status.parent
    respond_to do |format|
      if @transaction.save
        if !@transaction_liq.nil? && @transaction_liq.description == 'LIQUIDADA'
          format.html { redirect_to pendings_path }
        else
          format.html { redirect_to transactions_path }
        end
        format.json { render :show, status: :created, location: @transaction_detail }
      else
        format.html { render :new }
        format.json { render json: @transaction_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /transactions/change_status
  def devolucion
    # TODO: THIS CAN BE HANDLE BY A BETTER WAY, GETS THE DESCRIPTION TEXT OF THE BUTTON
    # AFTER SEND AS A PARAMETER AND GETS IN THIS METHOD
    # ALSO THIS METHOD CAN BE ELIMINATED AND USE ONLY CHANGE_STATUS
    @transaction.status = Status.find_by_description('DEVOLUCION')
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path }
        format.json { render :show, status: :created, location: @transaction_detail }
      else
        format.html { render :new }
        format.json { render json: @transaction_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # POST /transactions/change_status
  def not_delivery
    # TODO: THIS CAN BE HANDLE BY A BETTER WAY, GETS THE DESCRIPTION TEXT OF THE BUTTON
    # AFTER SEND AS A PARAMETER AND GETS IN THIS METHOD
    # ALSO THIS METHOD CAN BE ELIMINATED AND USE ONLY CHANGE_STATUS
    @transaction.status = Status.find_by_description('NO ENTREGADA')
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path }
        format.json { render :show, status: :created, location: @transaction_detail }
      else
        format.html { render :new }
        format.json { render json: @transaction_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  def asign_courier
    log = ActionLog.new
    log.transaction_id = @transaction.id
    log.user_id = current_dealer.id
    log.user_name = current_dealer.email
    courier = Dealer.find_by_id(transaction_params[:courier_id])
    @transaction.courier = courier
    log.action = "Courier asigned #{@transaction.status.description} to #{@transaction.status.parent.description}"
    log.date_time = DateTime.now
    log.save
    @transaction.status = @transaction.status.parent
    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path, turbolinks: false }
      else
        format.json { render json: courier.to_json, status: :not_found }
      end
    end
  end

  def delivered
    @transactions_query = Transaction.delivered_courier('SALE', current_dealer.id).ransack(params[:q])
    @transactions = @transactions_query.result(distinct: true)
  end

  def pendings
    @transactions_query = Transaction.delivered_liq('SALE').ransack(params[:q])
    @transactions = @transactions_query.result(distinct: true).page(params[:page])
    @not_pendings = false
  end

  def pendings_not
    @transactions_query = Transaction.not_delivered_liq('SALE').ransack(params[:q])
    @transactions = @transactions_query.result(distinct: true).page(params[:page])
    @not_pendings = true
    render :pendings
  end

  def on_route
    @transactions_query = Transaction.watching_to_deliver('SALE').ransack(params[:q])
    @pending_to_deliver = @transactions_query.result(distinct: true)
  end

  def return_to_stock
    log = ActionLog.new
    log.transaction_id = @transaction.id
    log.user_id = current_dealer.id
    log.user_name = current_dealer.email
    @transaction.transaction_details.each do |td|
      product = Product.find(td.product.id)
      product.quantity += td.quantity
      product.balance = product.quantity

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/edit.html.haml
- model_class = Transaction
- content_for :title, t('helpers.titles.edit', model: model_class.model_name.human.titleize)
= render 'form', transaction: @transaction, action: t('helpers.titles.edit', model: model_class.model_name.human)

app/views/transactions/index.html.haml
=# javascript_include_tag 'data_table_init'

:javascript
  $(function() {
    $('.downloadBtn').click(function(e) {
      if (confirm('Quiere cambiar de estado esta orden?')) {
        /*$.post('/transactions/' + gon.transaction.id + '/change_status', function(data) {
          console.log('done');
          const url_path = '/transactions/';
          document.location.href = url_path;
        });*/
        setTimeout(function(){
          location.reload();
        }, 2000);
      } else {
        e.preventDefault();
        e.stopPropagation();
        return;
      }
    });
    $('select').select2();
    $('.select_change').change(function(data) {
      console.log($(this).select2('data')[0].text);
      console.log($("#dialog-confirm"));
      if ($(this).select2('data')[0].text == 'Por favor seleccione') return;
      if(confirm("Quiere asignar esta orden al vendedor: " + $(this).select2('data')[0].text + "?")) {
        $.ajax('/asign_courier/', {type: 'POST', data: { transaction_id: $(this)[0].id, transaction: { courier_id: $(this).val() }}}
        ).done(function() {
          const url_path = '/transactions/';
          document.location.href = url_path;
        });
      } else {
        return;
      }
    });
    $('#change_status').click(function(e) {
      console.log(e);
      if (confirm('Esta seguro que quiere cambiar de estado esta orden?')) {
        console.log('success');
        $(this).hide();
      } else {
        e.preventDefault();
        e.stopPropagation();
        return;
      }
    });
    if (gon.status_filter != null) {
      $('#q_status_id_eq').val(gon.status_filter);
    }
  });

- model_class = Transaction
- content_for :title, model_class.model_name.human.pluralize(I18n.locale).titleize

- unless notice.nil?
  = bootstrap_notice(notice, alert.nil? ? 'success' : 'danger')

= bootstrap_card 'Filtros' do
  = search_form_for @transactions_query, url: transactions_path, html: {method: :get, class: 'form-inline'} do |f|
    .form-group
      .row.row-custom
        .col
          = f.label :id
        .col
          = bootstrap_text_field(f, :id_eq, model_class.human_attribute_name(:id))
    .form-group
      .row.row-custom
        .col
          = f.label :client
        .col
          = bootstrap_text_field(f, :client_cont, model_class.human_attribute_name(:client))
    .form-group
      .row.row-custom
        .col
          = f.label :tracking_number
        .col
          = bootstrap_text_field(f, :tracking_number_cont, model_class.human_attribute_name(:tracking_number))
    .form-group
      .row.row-custom
        .col{hidden:true}
          = f.label :created_at
        .col
          %div{hidden: true}
            = bootstrap_text_field(f, :created_at_between, model_class.human_attribute_name(:created_at))
          %label{:for => "from"} Fecha inicial
          %input#from{:name => "from", :type => "text",  class: 'form-control'}/
          %label{:for => "to"} Fecha final
          %input#to{:name => "to", :type => "text", class: 'form-control'}/
    .form-group
      .row.row-custom
        .col
          = f.label :status_id
        .col
          = f.collection_select :status_id_eq, Status.all, :id, :description, { prompt: true }, { class: 'form-control' }
    .form-group
      .row.row-custom
        .col
          = f.label :transportista
        .col
          = f.collection_select :carrier_id_eq, Carrier.all, :id, :name, { prompt: true }, { class: 'form-control' }
    .form-group
      .row.row-custom
        .col
          = f.label :mensajero
        .col
          = f.collection_select :courier_id_eq, Dealer.where(courier: true), :id, :custom_name, { prompt: true }, { class: 'form-control' }
    .form-group
      .row.row-custom
        .col
          = f.label ''
        .col
          = bootstrap_submit_button(f, 'Buscar')
          - if current_dealer.admin?
            =# bootstrap_button('primary', 'Exportar a excel', 'file-excel-o', transactions_path(format: :csv), 'get')
    .form-group
      .row.row-custom
        .col
          = f.label ''
        .col
          = clear_filter title: 'Borrar filtros', class: 'btn btn-primary', data: {confirm: 'Quieres borrar los filtros?', my_data: 'something'}

= bootstrap_card t('.title', :default => t('general.list', model: model_class.model_name.human.pluralize(I18n.locale))) do
  = will_paginate @transactions, renderer: BootstrapPagination::Rails
  .table-responsive
    %table#dataTable.table.table-bordered{:cellspacing => "0", :width => "100%"}
      %thead
        %tr
          - unless current_dealer.courier?
            %th= model_class.human_attribute_name(:id)
            %th= model_class.human_attribute_name(:tracking_number)
          %th= model_class.human_attribute_name(:description)
          %th= model_class.human_attribute_name(:client)
          %th= model_class.human_attribute_name(:address2)
          - unless current_dealer.courier?
            %th= model_class.human_attribute_name(:created_at)
          %th= model_class.human_attribute_name(:phone)
          %th= model_class.human_attribute_name(:amount)
          - unless current_dealer.courier?
            %th= model_class.human_attribute_name(:status)
            %th= t('activerecord.attributes.dealer.courier_custom')
            %th= model_class.human_attribute_name(:carrier)
          %th= model_class.human_attribute_name(:dealer)
          - if current_dealer.courier?
            %th= model_class.human_attribute_name(:id)
          %th= t '.actions', :default => t("helpers.actions")
      %tbody
        - @transactions.each do |transaction|
          %tr
            - unless current_dealer.courier?
              %td= transaction.id
              %td= transaction.tracking_number
            %td
              - transaction.transaction_details.each do |td|
                %span= [td.product.custom_name_order, td.quantity].join(' | ')
            %td= transaction.client
            %td= transaction.address2
            - unless current_dealer.courier?
              %td= transaction.created_at.strftime('%d/%m/%Y')
            %td
              %a{href: "tel:#{transaction.phone}"}= transaction.phone
            %td= transaction.amount
            - unless current_dealer.courier?
              %td= transaction.status.description unless transaction.status.nil?
              %td= transaction.courier.custom_name unless transaction.courier.nil?
              %td= transaction.carrier.name unless transaction.carrier.nil?
            %td= transaction.dealer.custom_name unless transaction.dealer.nil?
            - if current_dealer.courier?
              %td= transaction.id
            %td
              - if transaction.type.int_value == 2 && !transaction.amount.nil? && transaction.amount > 0
                - if !transaction.status.parent.nil?
                  - if transaction.courier.nil? && !transaction.carrier.nil? && transaction.carrier.internal && (current_dealer.grocer? || current_dealer.admin?)
                    = collection_select 'couriers', :courier_id, Dealer.couriers, :id, :custom_name, { prompt: true }, { class: 'form-control select_change', id: transaction.id }
                  - elsif current_dealer.courier? || current_dealer.grocer? || current_dealer.admin?
                    - unless transaction.status.parent.description == 'LIQUIDADA (NO ENTREGADA)'
                      = bootstrap_button_ids('change_status', 'primary change_status', t('general.change_status', status: transaction.status.parent.description), 'arrow-right', transaction_change_status_path(transaction), 'post')
                  - if current_dealer.courier?
                    = bootstrap_button_ids('change_status', 'primary change_status', t('general.change_status', status: 'NO ENTREGADA'), 'arrow-right', transaction_not_delivery_path(transaction), 'post')
                  - if !(current_dealer.courier? || current_dealer.grocer? || current_dealer.admin?) && !transaction.carrier.internal && transaction.on_route?('SALE')
                    = bootstrap_button_ids('change_status', 'primary change_status vendedor', t('general.change_status', status: transaction.status.parent.description), 'arrow-right', transaction_change_status_path(transaction), 'post')
              = bootstrap_button('success', nil, 'eye', transaction_transaction_details_path(transaction))
              = bootstrap_button('warning', nil, 'exclamation-triangle', edit_transaction_path(transaction)) if current_dealer.grocer? && transaction.url_reference.nil?
              - if transaction.open?('SALE')
                = bootstrap_button('warning', nil, 'exclamation-triangle', edit_transaction_path(transaction)) unless transaction.closed?('SALE')
              =# bootstrap_button_id('downloadBtn', 'warning', nil, 'download', transaction_view_tracking_path(transaction))
              - if transaction.closed?('SALE') && transaction.type.int_value == 2 && !transaction.carrier.internal? && !transaction.url_reference.nil? && current_dealer.grocer? || current_dealer.admin?
                = bootstrap_button_id('downloadBtn', 'warning downloadBtn', nil, 'download', transaction_view_tracking_path(transaction))
              - elsif transaction.type.int_value == 2 && !transaction.open?('SALE') && !transaction.carrier.internal? && !transaction.url_reference.nil? && current_dealer.grocer? || current_dealer.admin?
                = bootstrap_button_id('downloadBtn2', 'primary', nil, 'download', transaction.url_reference)
              - if (transaction.open?('SALE') || transaction.closed?('SALE')) || current_dealer.admin?
                = bootstrap_button_destroy(transaction)
              - if current_dealer.admin? && transaction.delivered?('SALE') || transaction.not_delivery?('SALE') && transaction.status != Status.find_by_description('REGRESADO A STOCK')
                = bootstrap_button_ids('change_status', 'primary change_status', 'Regresar a stock', 'arrow-right', transaction_return_to_stock_path(transaction), 'post')
    - unless current_dealer.grocer? || current_dealer.courier?
      %br/
      = bootstrap_button('primary', t('helpers.titles.new', model: model_class.model_name.human), 'plus', new_transaction_path)

app/views/transactions/new.html.haml
- model_class = Transaction
- content_for :title, t('helpers.titles.new', model: model_class.model_name.human.titleize)

= render 'form', transaction: @transaction, action: t('helpers.titles.new', model: model_class.model_name.human)

app/views/transactions/pendings.html.haml
=# javascript_include_tag 'data_table_init'

:javascript
  $(function() {
    $('#dataTable').DataTable({
      paging: true,
      searching: true,
      ordering: true,
      language: {
        search: 'Buscar',
        paginate: {
          first: 'Primero',
          previous: 'Anterior',
          next: 'Siguiente',
          last: 'Último'
        },
        info: 'Mostrando _START_ de _END_ registros',
        lengthMenu: 'Mostrar _MENU_ registros'
      },
      "footerCallback": function (row, data, start, end, display) {
        var api = this.api();
        api.columns(8, {
          page: 'current'
          }).every(function() {
            var sum = this
              .data()
              .reduce(function(a, b) {
                var x = parseFloat(a) || 0;
                var y = parseFloat(b) || 0;
                return x + y;
              }, 0);
            //console.log(sum); //alert(sum);
            $(this.footer()).html('Q ' + sum.toFixed(2));
          });
        }
      });
  });

- model_class = Transaction
- if @not_pendings
  - content_for :title, "Paquetes no entregados: #{@transactions.count}"
- else
  - content_for :title, model_class.model_name.human.pluralize(I18n.locale).titleize

- unless notice.nil?
  = bootstrap_notice(notice, alert.nil? ? 'success' : 'danger')

= bootstrap_card 'Filtros' do
  = search_form_for @transactions_query, url: @not_pendings ? pendings_not_delivered_path : pendings_path, html: {method: :get, class: 'form-inline'} do |f|
    .form-group
      .row.row-custom
        .col
          = f.label :id
        .col
          = bootstrap_text_field(f, :id_eq, model_class.human_attribute_name(:id))
    .form-group
      .row.row-custom
        .col
          = f.label :client
        .col
          = bootstrap_text_field(f, :client_cont, model_class.human_attribute_name(:client))
    .form-group
      .row.row-custom
        .col
          = f.label :tracking_number
        .col
          = bootstrap_text_field(f, :tracking_number_cont, model_class.human_attribute_name(:tracking_number))
    .form-group
      .row.row-custom
        .col
          = f.label :created_at
        .col
          = bootstrap_text_field(f, :created_at_date_equals, model_class.human_attribute_name(:created_at))
    .form-group
      .row.row-custom
        .col
          = f.label :mensajero
        .col
          = bootstrap_text_field(f, :courier_name_cont, model_class.human_attribute_name(:mensajero))
    .form-group
      .row.row-custom
        .col
          = f.label ''
        .col
          = bootstrap_submit_button(f, 'Buscar')
    .form-group
      .row.row-custom
        .col
          = f.label ''
        .col
          = clear_filter title: 'Borrar filtros', class: 'btn btn-primary', data: {confirm: 'Quieres borrar los filtros?', my_data: 'something'}

= bootstrap_card t('.title', :default => t('general.list', model: model_class.model_name.human.pluralize(I18n.locale))) do
  = will_paginate @transactions, renderer: BootstrapPagination::Rails
  .table-responsive
    %table#dataTable.table.table-bordered{:cellspacing => "0", :width => "100%"}
      %thead
        %tr
          %th= t '.actions', :default => t("helpers.actions")
          %th= model_class.human_attribute_name(:id)
          %th= model_class.human_attribute_name(:tracking_number)
          %th= model_class.human_attribute_name(:description)
          %th= model_class.human_attribute_name(:client)
          %th= model_class.human_attribute_name(:address2)
          %th= model_class.human_attribute_name(:created_at)
          %th= model_class.human_attribute_name(:phone)
          - unless current_dealer.grocer?
            %th= model_class.human_attribute_name(:amount)
          %th= model_class.human_attribute_name(:status)
          %th= model_class.human_attribute_name(:dealer)
          %th= model_class.human_attribute_name(:carrier)
        %tfoot
          %tr
            - if current_dealer.grocer? || current_dealer.courier?
              %th
            - else
              %th{colspan: 7}
            %th= model_class.human_attribute_name(:total).upcase
            %th
      %tbody
        - @transactions.each do |transaction|
          %tr
            %td
              - if transaction.type.int_value == 2 && !transaction.amount.nil? && transaction.amount > 0
                - unless transaction.status == Status.find_by_description('NO ENTREGADA')
                  = bootstrap_button('primary', t('general.change_status', status: transaction.status.parent.description), 'arrow-right', transaction_change_status_path(transaction), 'post')
              = bootstrap_button('success', nil, 'eye', transaction_transaction_details_path(transaction))
              - if transaction.open?('SALE')
                = bootstrap_button('warning', nil, 'exclamation-triangle', edit_transaction_path(transaction)) unless transaction.closed?('SALE')
              - if current_dealer.admin? && transaction.open?('SALE')
                = bootstrap_button_destroy(transaction)
              - if current_dealer.admin? && transaction.status != Status.find_by_description('ENTREGADA')
                = bootstrap_button_ids('change_status', 'primary change_status', 'Regresar a stock', 'arrow-right', transaction_return_to_stock_path(transaction), 'post')
            %td= transaction.id
            %td= transaction.tracking_number
            %td
              - transaction.transaction_details.each do |td|
                %span= [td.product.custom_name_order, td.quantity].join(' | ')
            %td= transaction.client
            %td= transaction.address2
            %td= transaction.created_at.strftime('%d/%m/%Y')
            %td= transaction.phone
            - unless current_dealer.grocer?
              %td= transaction.amount
            %td= transaction.status.description unless transaction.status.nil?
            %td= transaction.dealer.custom_name unless transaction.dealer.nil?
            - if transaction.carrier.internal?
              %td= transaction.courier.custom_name unless transaction.courier.nil?
            - else
              %td= transaction.carrier.name unless transaction.carrier.nil?

    - unless current_dealer.grocer? || current_dealer.courier?
      %br/
      = bootstrap_button('primary', t('helpers.titles.new', model: model_class.model_name.human), 'plus', new_transaction_path)

app/views/transactions/show.html.haml
%p#notice= notice

%p
  %b Description:
  = @transaction.description
%p
  %b Client:
  = @transaction.client
%p
  %b Address:
  = @transaction.address
%p
  %b Address2:
  = @transaction.address2
%p
  %b Phone:
  = @transaction.phone
%p
  %b Amount:
  = @transaction.amount
%p
  %b Status:
  = @transaction.status
%p
  %b Dealer:
  = @transaction.dealer
%p
  %b Type:
  = @transaction.type_id
%p
  %b Tracking number:
  = @transaction.tracking_number
%p
  %b Carrier:
  = @transaction.carrier

= link_to 'Edit', edit_transaction_path(@transaction)
\|
= link_to 'Back', transactions_path