config/routes.rb
Rails.application.routes.draw do
  resources :municipalities
  get 'municipalities_list', to: 'municipalities#list', as: 'municipalities_by_department'
  resources :departments
  resources :pieces
  resources :villages
  get 'villages_list', to: 'villages#list', as: 'villages_by_municipality'
  resources :deliveries
  resources :parameters
  resources :transactions do
    resources :transaction_details
    post 'close_order', to: 'close_order', as: 'close_order'
    post 'change_status', to: 'change_status', as: 'change_status'
    post 'devolucion', to: 'devolucion', as: 'devolucion'
    post 'not_delivery', to: 'not_delivery', as: 'not_delivery'
    get '/view_tracking', to: 'transactions#view_tracking', as: 'view_tracking'
    post '/return_stock', to: 'transactions#return_to_stock', as: 'return_to_stock'
  end
  get '/delivered', to: 'transactions#delivered', as: 'delivered'
  get '/pendings', to: 'transactions#pendings', as: 'pendings'
  get '/pendings_not', to: 'transactions#pendings_not', as: 'pendings_not_delivered'
  get '/on_route', to: 'transactions#on_route', as: 'on_route'
  post '/asign_courier', to: 'transactions#asign_courier', as: 'asign_courier'
  get '/restocks', to: 'transactions#restocks', as: 'restocks'
  resources :products
  devise_for :dealers, controllers: {
    sessions: 'dealers/sessions'
  }
  resources :statuses
  resources :carriers
  resources :characteristics
  resources :categories
  resources :dealers
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      get 'product_availability', to: 'inventory_utils#check_inventory_qty', as: 'product_availability'
    end
  end

  get '/reports', to: 'reports#index', as: 'reports'
  get '/earning', to: 'reports#earning_report', as: 'earning_report'
  get '/delivery', to: 'reports#delivery_report', as: 'delivery_report'

  root 'dashboard#index'
end

app/models/parameter.rb
# frozen_string_literal: true

class Parameter < ApplicationRecord
  has_many :transactions, class_name: :Transaction, primary_key: 'int_value', foreign_key: 'type_id'
  scope :transaction_types, lambda {
    where(tag: 'TRANSACTION_TYPE')
  }

  scope :transaction_type_in, -> { where(tag: 'TRANSACTION_TYPE', int_value: 1) }

  scope :transaction_type_out, -> { where(tag: 'TRANSACTION_TYPE', int_value: 2) }

  scope :transaction_type_return, -> { where(tag: 'TRANSACTION_TYPE', int_value: 3) }

  scope :service_types, -> { where(tag: 'SERVICE_TYPE') }
  scope :sender_info, -> { where(tag: 'SENDER_INFO') }
  scope :auth, -> { where(tag: 'AUTHENTICATION') }
end

app/controllers/parameters_controller.rb
class ParametersController < ApplicationController
  before_action :set_parameter, only: [:show, :edit, :update, :destroy]

  # GET /parameters
  # GET /parameters.json
  def index
    @parameters = Parameter.all
  end

  # GET /parameters/1
  # GET /parameters/1.json
  def show
  end

  # GET /parameters/new
  def new
    @parameter = Parameter.new
  end

  # GET /parameters/1/edit
  def edit
  end

  # POST /parameters
  # POST /parameters.json
  def create
    @parameter = Parameter.new(parameter_params)

    respond_to do |format|
      if @parameter.save
        format.html { redirect_to @parameter, notice: 'Parameter was successfully created.' }
        format.json { render :show, status: :created, location: @parameter }
      else
        format.html { render :new }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parameters/1
  # PATCH/PUT /parameters/1.json
  def update
    respond_to do |format|
      if @parameter.update(parameter_params)
        format.html { redirect_to @parameter, notice: 'Parameter was successfully updated.' }
        format.json { render :show, status: :ok, location: @parameter }
      else
        format.html { render :edit }
        format.json { render json: @parameter.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parameters/1
  # DELETE /parameters/1.json
  def destroy
    @parameter.destroy
    respond_to do |format|
      format.html { redirect_to parameters_url, notice: 'Parameter was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_parameter
      @parameter = Parameter.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def parameter_params
      params.require(:parameter).permit(:tag, :description, :int_value, :text_value)
    end
end

app/helpers/parameters_helper.rb
module ParametersHelper
end

app/views/parameters/_form.html.haml
= form_for @parameter do |f|
  - if @parameter.errors.any?
    #error_explanation
      %h2= "#{pluralize(@parameter.errors.count, "error")} prohibited this parameter from being saved:"
      %ul
        - @parameter.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :tag
    = f.text_field :tag
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :int_value
    = f.text_field :int_value
  .field
    = f.label :text_value
    = f.text_field :text_value
  .actions
    = f.submit 'Save'

app/views/parameters/edit.html.haml
%h1 Editing parameter

= render 'form'

= link_to 'Show', @parameter
\|
= link_to 'Back', parameters_path

app/views/parameters/index.html.haml
= javascript_include_tag 'data_table_init'

- model_class = Parameter
- content_for :title, model_class.model_name.human.pluralize(I18n.locale).titleize

- unless notice.nil?
  = bootstrap_notice(notice, alert.nil? ? 'success' : 'danger')
= bootstrap_card t('.title', :default => t('general.list', model: model_class.model_name.human.pluralize(I18n.locale))) do
  .table-responsive
    %table#dataTable.table.table-bordered{:cellspacing => "0", :width => "100%"}
      %tr
        %th Tag
        %th Description
        %th Int value
        %th Text value
        %th
        %th
        %th
      %tbody
        - @parameters.each do |parameter|
          %tr
            %td= parameter.tag
            %td= parameter.description
            %td= parameter.int_value
            %td= parameter.text_value
            %td= link_to 'Show', parameter
            %td= link_to 'Edit', edit_parameter_path(parameter)
            %td= link_to 'Destroy', parameter, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Parameter', new_parameter_path

app/views/parameters/new.html.haml
%h1 New parameter

= render 'form'

= link_to 'Back', parameters_path

app/views/parameters/show.html.haml
%p#notice= notice

%p
  %b Tag:
  = @parameter.tag
%p
  %b Description:
  = @parameter.description
%p
  %b Int value:
  = @parameter.int_value
%p
  %b Text value:
  = @parameter.text_value

= link_to 'Edit', edit_parameter_path(@parameter)
\|
= link_to 'Back', parameters_path